version: "3"
services:
  angular:
    build: https://github.com/Meeting-App-ISAAC/Frontend-Tablets.git
    #image: "isaak-frontend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    networks:
      - backend
    depends_on:
      - java
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  java: 
    build: https://github.com/Meeting-App-ISAAC/MeetingRoom-Backend.git
    #image: "isaak-backend"
    volumes:
      - ./admin.txt:/admin.txt
      - ./auth.properties:/auth.properties
      - ./config.properties:/config.properties
      - ./roomdata.txt:/roomdata.txt
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure       
networks:
  backend: